language: node_js
node_js:
  - lts/*
script:
  - npm run lint
  - npm run test
branches:
  only:
    - master
addons:
  postgresql: 11
  apt:
    packages:
      - postgresql-11-postgis-2.5
before_script:
  - cp .env.travis .env
  - NODE_ENV=test npm run db:create
