language: node_js
node_js:
  - lts/*
script:
  - npm run lint
  - npm run test
branches:
  only:
    - master
env:
  - TEST_DATABASE_URL=postgres://postgres@localhost/aps7-test
addons:
  postgresql: 11
  apt:
    packages:
      - postgresql-11-postgis-2.5
before_script:
  - NODE_ENV=test npm run db:create
